import { CategoryMetadata } from "@/types/categoryType";

export const DEFAULT_CATEGORY_METADATA: CategoryMetadata = {
  category: '',
  course: '',
  requiredTier: 'free',
  image: 'https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5KkQtwIbr79T0mSRj6eAJqPf4kEid2ncgM5Nu',
  description: 'Twoja własna kategoria testów',
  duration: [25, 40, 60],
  popularity: 'Kategoria niestandardowa',
  status: true,
  numberOfQuestions: [10, 40]
};

export const CATEGORY_METADATA: Record<string, CategoryMetadata> = {
  "opiekun-medyczny": {
    category: "opiekun-medyczny",
    course: "opiekun-medyczny",
    requiredTier: "basic",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5hAALGCKaPSlWXcFVLft4M8kAgI2ECx19u7JN",
    description: "Przygotuj się do egzaminu Opiekuna Medycznego z naszymi kompleksowymi testami i pytaniami. Bogata baza pytań, która pomoże Ci w 100% przygotować sie do egzaminu państwowego i zdać za pierwszym razem!",
    duration: [25, 40, 60],
    popularity: "Bardzo popularny",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Testy - Kategoria: Opiekun Medyczny",
    keywords: ["opiekun", "med-14", "egzamin", "testy", "pytania", "zagadnienia", "medyczno-pielęgnacyjnych", "opiekuńczych", "baza"],
  },
  "anatomia": {
    category: "anatomia",
    course: "pielegniarstwo",
    requiredTier: "basic",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k52G1vt6SEBiUD8sVXHObYqkj3TNfo4PKMGg6J",
    description: "Kompleksowe testy z anatomii dla studentów pielęgniarstwa. Poznaj budowę ciała ludzkiego, układy narządowe, struktury anatomiczne i ich funkcje. Idealne przygotowanie do egzaminów i praktyki zawodowej.",
    duration: [25, 40, 60],
    popularity: "Sprawdź swoją wiedzę już teraz!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Anatomia - Testy dla Kierunku Pielęgniarstwo",
    keywords: ["anatomia", "pielęgniarstwo", "budowa ciała", "układy narządowe", "struktura anatomiczna", "kości", "mięśnie", "narządy", "egzamin pielęgniarski", "testy wiedzy", "pytania egzaminacyjne"],
  },
   "fizjologia": {
    category: "fizjologia",
    course: "pielegniarstwo",
    requiredTier: "basic",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5UN2L0ZIxs2k5EyuGdN4SRigYP6qreJDvtVZl",
    description: "Kompleksowe testy z fizjologii dla studentów pielęgniarstwa, obejmujące wszystkie istotne zagadnienia wymagane na egzaminach i w codziennej praktyce zawodowej. Sprawdź swoją wiedzę z układów organizmu, procesów fizjologicznych i funkcji życiowych.",
    duration: [25, 40, 60],
    popularity: "Sprawdź swoją wiedzę już teraz!",
    status: true,
    numberOfQuestions: [10,40],
    title: "Fizjologia - Testy dla Kierunku Pielęgniarstwo",
    keywords: ["fizjologia", "pielęgniarstwo", "układ krążenia", "układ oddechowy", "zdrowie", "opieka", "egzamin pielęgniarski", "testy wiedzy", "pytania egzaminacyjne"],
  },
  "biochemia-biofizyka": {
    category: "biochemia-biofizyka",
    course: "pielegniarstwo",
    requiredTier: "basic",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5bHmZPN10lAXCNeHTtQdjmyVvPInzGfZrLsw9",
    description: "Testy z biochemii i biofizyki dla studentów pielęgniarstwa. Opanuj procesy biochemiczne w organizmie, metabolizm, białka, węglowodany, lipidy oraz podstawy biofizyki. Przygotuj się kompleksowo do egzaminu.",
    duration: [25, 40, 60],
    popularity: "Sprawdź swoją wiedzę już teraz!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Biochemia z Biofizyką - Testy dla Kierunku Pielęgniarstwo",
    keywords: ["biochemia", "biofizyka", "pielęgniarstwo", "metabolizm", "białka", "enzymy", "homeostaza", "procesy biochemiczne", "egzamin pielęgniarski", "testy wiedzy", "pytania egzaminacyjne"],
  },
  "socjologia": {
    category: "socjologia",
    course: "pielegniarstwo",
    requiredTier: "basic",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5nt6oObL9GQYxNri4Uw0MejlVEP63mgKp18FO",
    description: "Testy z socjologii dla studentów pielęgniarstwa. Poznaj struktury społeczne, role zawodowe w ochronie zdrowia, komunikację interpersonalną oraz socjologiczne aspekty pracy z pacjentem. Przygotuj się do egzaminu z nauk społecznych.",
    duration: [25, 40, 60],
    popularity: "Sprawdź swoją wiedzę już teraz!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Socjologia - Testy dla Kierunku Pielęgniarstwo",
    keywords: ["socjologia", "pielęgniarstwo", "struktury społeczne", "komunikacja", "relacje interpersonalne", "pacjent", "opieka zdrowotna", "role społeczne", "egzamin pielęgniarski", "testy wiedzy", "pytania egzaminacyjne"],
  },
  "mikrobiologia-parazytologia": {
    category: "mikrobiologia-parazytologia",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5QNXUuJYf6PZ5eKuhFM9REHkAy4n7s3aNYmWi",
    description: "Zaawansowane testy z mikrobiologii i parazytologii dla studentów pielęgniarstwa. Poznaj bakterie, wirusy, grzyby, pasożyty oraz mechanizmy zakażeń. Niezbędna wiedza do pracy w ochronie zdrowia.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Mikrobiologia z Parazytologią - Testy Premium",
    keywords: ["mikrobiologia", "parazytologia", "bakterie", "wirusy", "grzyby", "pasożyty", "zakażenia", "patogeny", "egzamin pielęgniarski", "testy premium"],
  },
  "psychologia": {
    category: "psychologia",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5kbdfnVA5zS3pZrqLGeEj7tHO6cdWvCYm4N2R",
    description: "Testy z psychologii dla przyszłych pielęgniarek. Opanuj psychologię kliniczną, komunikację z pacjentem, wsparcie emocjonalne, mechanizmy obronne oraz psychologiczne aspekty choroby i leczenia.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Psychologia - Testy Premium dla Pielęgniarstwa",
    keywords: ["psychologia", "pielęgniarstwo", "psychologia kliniczna", "komunikacja z pacjentem", "wsparcie emocjonalne", "choroba", "pacjent", "testy premium"],
  },
  "pedagogika": {
    category: "pedagogika",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5bp3ERm10lAXCNeHTtQdjmyVvPInzGfZrLsw9",
    description: "Testy z pedagogiki dla studentów pielęgniarstwa. Edukacja zdrowotna pacjentów, metody nauczania, promocja samoopieki oraz pedagogiczne aspekty pracy z różnymi grupami wiekowymi.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Pedagogika - Testy Premium dla Pielęgniarstwa",
    keywords: ["pedagogika", "pielęgniarstwo", "edukacja zdrowotna", "nauczanie pacjentów", "promocja zdrowia", "metody dydaktyczne", "testy premium"],
  },
  "zdrowie-publiczne": {
    category: "zdrowie-publiczne",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k54pC04HH9lLqODmv7er0SPRQB8C9VnfbTHisc",
    description: "Testy ze zdrowia publicznego dla pielęgniarstwa. Epidemiologia, profilaktyka, polityka zdrowotna, statystyka medyczna oraz organizacja systemu ochrony zdrowia w Polsce.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Zdrowie Publiczne - Testy Premium",
    keywords: ["zdrowie publiczne", "epidemiologia", "profilaktyka", "polityka zdrowotna", "statystyka medyczna", "ochrona zdrowia", "pielęgniarstwo", "testy premium"],
  },
  "prawo-medyczne": {
    category: "prawo-medyczne",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5JajIrkmQWsLSvF0ZVh7qXdCNxbjatwczey8g",
    description: "Testy z prawa medycznego dla pielęgniarek. Prawa pacjenta, odpowiedzialność zawodowa, dokumentacja medyczna, tajemnica zawodowa oraz regulacje prawne w ochronie zdrowia.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Prawo Medyczne - Testy Premium",
    keywords: ["prawo medyczne", "prawa pacjenta", "odpowiedzialność zawodowa", "dokumentacja medyczna", "tajemnica lekarska", "regulacje prawne", "pielęgniarstwo", "testy premium"],
  },
  "podstawy-pielegniarstwa": {
    category: "podstawy-pielegniarstwa",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5gOhTeFK1JZolbvwfgWCAFPh8xz9BIKNsVjGk",
    description: "Kompleksowe testy z podstaw pielęgniarstwa. Podstawowe procedury, techniki pielęgnacyjne, higiena, bezpieczeństwo pacjenta, standardy opieki oraz fundamenty zawodu pielęgniarki.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Podstawy Pielęgniarstwa - Testy Premium",
    keywords: ["podstawy pielęgniarstwa", "procedury pielęgnacyjne", "techniki", "higiena", "bezpieczeństwo pacjenta", "standardy opieki", "zawód pielęgniarki", "testy premium"],
  },
  "etyka-zawodowa": {
    category: "etyka-zawodowa",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5KqquTG6br79T0mSRj6eAJqPf4kEid2ncgM5N",
    description: "Testy z etyki zawodu pielęgniarki. Kodeks etyki, dylematy etyczne, godność pacjenta, autonomia, poufność oraz wartości etyczne w codziennej praktyce pielęgniarskiej.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Etyka Zawodu Pielęgniarki - Testy Premium",
    keywords: ["etyka", "kodeks etyki", "dylematy etyczne", "godność pacjenta", "autonomia", "wartości etyczne", "zawód pielęgniarki", "testy premium"],
  },
  "promocja-zdrowia": {
    category: "promocja-zdrowia",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k52bP49YSEBiUD8sVXHObYqkj3TNfo4PKMGg6J",
    description: "Testy z promocji zdrowia dla pielęgniarstwa. Style życia, profilaktyka chorób, edukacja zdrowotna, zdrowe nawyki oraz programy promocji zdrowia w różnych grupach społecznych.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Promocja Zdrowia - Testy Premium",
    keywords: ["promocja zdrowia", "profilaktyka", "edukacja zdrowotna", "zdrowy styl życia", "prewencja", "nawyki zdrowotne", "pielęgniarstwo", "testy premium"],
  },
  "zakazenia-szpitalne": {
    category: "zakazenia-szpitalne",
    course: "pielegniarstwo",
    requiredTier: "premium",
    image: "https://utfs.io/a/zw3dk8dyy9/UVAwLrIxs2k5s4bwXrWj5zfQ3u7I8bUgG0ydxCaMOwLKeVP6",
    description: "Zaawansowane testy o zakażeniach szpitalnych. Profilaktyka zakażeń, sterylizacja, dezynfekcja, aseptyka, antyseptyka, procedury izolacji oraz kontrola zakażeń w środowisku szpitalnym.",
    duration: [25, 40, 60],
    popularity: "Treść Premium!",
    status: true,
    numberOfQuestions: [10, 40],
    title: "Zakażenia Szpitalne - Testy Premium",
    keywords: ["zakażenia szpitalne", "profilaktyka", "sterylizacja", "dezynfekcja", "aseptyka", "antyseptyka", "kontrola zakażeń", "higiena szpitalna", "testy premium"],
  }
};
