import type { ErrorCategory } from '@/types/challengeTypes'

/** Challenge types generated by AI — order-steps stays deterministic. */
export type AiChallengeType = 'knowledge-quiz' | 'spot-error' | 'scenario-based'

export const AI_CHALLENGE_TYPES: AiChallengeType[] = [
  'knowledge-quiz',
  'spot-error',
  'scenario-based',
]

export interface GeneratedQuizQuestion {
  id: string
  question: string
  options: string[]
  correctAnswer: number
  explanation?: string | null
}

export interface GeneratedKnowledgeQuiz {
  procedureName: string
  questions: GeneratedQuizQuestion[]
}

export interface GeneratedSpotErrorStep {
  id: string
  step: string
  isCorrect: boolean
  errorCategory?: ErrorCategory | null
  explanation?: string | null
}

export interface GeneratedSpotErrorQuiz {
  procedureName: string
  steps: GeneratedSpotErrorStep[]
}

export interface GeneratedScenarioQuiz {
  procedureName: string
  scenario: string
  question: string
  options: string[]
  correctAnswer: number
  explanation?: string | null
}

export type GeneratedQuizData =
  | GeneratedKnowledgeQuiz
  | GeneratedSpotErrorQuiz
  | GeneratedScenarioQuiz

/** Client-safe view: correct answers and per-item explanations stripped. */
export interface GeneratedQuizPlayView {
  quizId: string
  procedureId: string
  procedureName: string
  challengeType: AiChallengeType
  questions?: Array<{ id: string; question: string; options: string[] }>
  steps?: Array<{ id: string; step: string }>
  scenario?: string
  question?: string
  options?: string[]
}
