/**
 * Step 2: Sync Clerk publicMetadata from the exported users file.
 *
 * Reads scripts/users-export.json (generated by export-users.ts) and
 * patches each user's Clerk publicMetadata.ownedCourses accordingly.
 *
 * - Always fetches current Clerk metadata before patching — never blindly overwrites
 * - Skips users whose metadata is already correct
 * - Logs ✓ updated / ⏭ skipped / ✗ failed per user
 * - If a Clerk user no longer exists (deleted account), logs as failed and continues
 *
 * Run with:
 *   npx tsx scripts/sync-clerk-metadata.ts
 *
 * Requires in .env.local:
 *   CLERK_SECRET_KEY=
 */

import 'dotenv/config'
import fs from 'fs'
import path from 'path'

const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY

if (!CLERK_SECRET_KEY) {
  console.error('Error: CLERK_SECRET_KEY is not set.')
  process.exit(1)
}

const exportPath = path.join(process.cwd(), 'scripts', 'users-export.json')

if (!fs.existsSync(exportPath)) {
  console.error('Error: scripts/users-export.json not found.')
  console.error('Run export first: npx tsx scripts/export-users.ts')
  process.exit(1)
}

type UserExport = {
  userId: string
  ownedCourses: string[]
}

async function getClerkUser(userId: string) {
  const res = await fetch(`https://api.clerk.com/v1/users/${userId}`, {
    headers: { Authorization: `Bearer ${CLERK_SECRET_KEY}` },
  })
  if (res.status === 404) return null
  if (!res.ok) throw new Error(`Clerk getUser failed: ${res.status}`)
  return res.json()
}

async function updateClerkMetadata(userId: string, existingMeta: Record<string, unknown>, ownedCourses: string[]) {
  const res = await fetch(`https://api.clerk.com/v1/users/${userId}`, {
    method: 'PATCH',
    headers: {
      Authorization: `Bearer ${CLERK_SECRET_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      public_metadata: { ...existingMeta, ownedCourses },
    }),
  })
  if (!res.ok) throw new Error(`Clerk updateUser failed: ${res.status}`)
}

async function syncClerkMetadata() {
  const users: UserExport[] = JSON.parse(fs.readFileSync(exportPath, 'utf-8'))

  console.log(`Loaded ${users.length} users from users-export.json`)
  console.log('---')

  let updated = 0
  let skipped = 0
  let failed = 0
  let notFound = 0

  for (const { userId, ownedCourses } of users) {
    try {
      const clerkUser = await getClerkUser(userId)

      if (!clerkUser) {
        console.warn(`⚠  ${userId} — not found in Clerk (account deleted), skipping`)
        notFound++
        continue
      }

      const existingMeta: Record<string, unknown> = clerkUser.public_metadata ?? {}
      const currentCourses: string[] = (existingMeta.ownedCourses as string[]) ?? []
      const alreadyCorrect =
        JSON.stringify([...currentCourses].sort()) === JSON.stringify([...ownedCourses].sort())

      if (alreadyCorrect) {
        console.log(`⏭  ${userId} — already correct, skipping`)
        skipped++
        continue
      }

      await updateClerkMetadata(userId, existingMeta, ownedCourses)
      console.log(`✓  ${userId} — ownedCourses: [${ownedCourses.join(', ') || 'none'}]`)
      updated++
    } catch (err) {
      console.error(`✗  ${userId} — ${err}`)
      failed++
    }
  }

  console.log('---')
  console.log(`Done.`)
  console.log(`  ✓ Updated:   ${updated}`)
  console.log(`  ⏭ Skipped:   ${skipped}`)
  console.log(`  ⚠ Not found: ${notFound}`)
  console.log(`  ✗ Failed:    ${failed}`)
}

syncClerkMetadata().catch((err) => {
  console.error('Sync failed:', err)
  process.exit(1)
})
